function RegisterRoutes() {
    return {
        customRoutes: [
            {route: '', template: 'home/template', controller: 'home'},
            {route: 'sign-in', template: 'auth/sign-in', controller: 'auth', auth: false},
            {route: 'forgot-password', template: 'auth/forgot-password', controller: 'auth', auth: false},
            {route: 'register', template: 'auth/register', controller: 'auth', auth: false},
            {route: 'profile', template: 'auth/profile', controller: 'profile'},
            {route: 'unauthorized', template: 'auth/unauthorized', controller: 'unauthorized'},
            {route: 'out-of-service', template: 'auth/out-of-service', controller: 'outOfService', auth: false},
            {route: 'settings', template: 'settings/template', controller: 'settings'},
            {route: 'forms-procedures', template: 'formsProcedures/template', controller: 'formsProcedures'},
            {route: 'forms-procedures/add', template: 'formsProcedures/procedure-add', controller: 'formsProcedureAdd'},
            {route: 'forms-procedures/:id/edit', template: 'formsProcedures/procedure-add', controller: 'formsProcedureEdit'},
            {route: 'forms-procedures/:id', template: 'formsProcedures/procedure', controller:'procedure' },
            {route: 'forms-question-bank', template: 'formsQuestionBank/template', controller: 'formsQuestionBank'},
            {route: 'forms-question-bank/add', template: 'formsQuestionBank/questionBank-add', controller: 'formsQuestionBankAdd'},
            {route: 'forms-question-bank/:id/edit', template: 'formsQuestionBank/questionBank-add', controller: 'formsQuestionBankEdit'},
            {route: 'forms-master', template: 'formsMaster/template', controller: 'formsMaster'},
            {route: 'forms-master/add', template: 'formsMaster/master-add', controller: 'formsMasterAdd'},
            {route: 'forms-master/:id', template: 'formsMaster/template', controller: 'formsMaster'},
            {route: 'forms-master/:id/edit', template: 'formsMaster/master-add', controller: 'formsMasterEdit'},
            {route: 'forms-master/:id/entry/list', template: 'formsMaster/master-entry-listing', controller: 'formsMasterEntryListing'},
            {route: 'forms-master/:id/entry', template: 'formsMaster/master-entry', controller: 'formsMasterEntry'},
            {route: 'forms-master/:id/entry/edit', template: 'formsMaster/master-entry', controller: 'formsMasterEntryEdit'},
            {route: 'forms-search', template: 'formsSearch/template', controller: 'formsSearch'},
            {route: 'forms-category', template: 'formsCategories/template', controller: 'formsCategory'},
            {route: 'forms-category/add', template: 'formsCategories/category-add', controller: 'formsCategoryAdd'},
            {route: 'forms-category/:id/edit', template: 'formsCategories/category-add', controller: 'formsCategoryEdit'},
            {route: 'forms-usergroups', template: 'formsUserGroups/template', controller: 'formsUsergroups'},
            {route: 'forms-usergroups/add', template: 'formsUserGroups/usergroup-add', controller: 'formsUsergroupAdd'},
            {route: 'forms-usergroups/:id', template: 'formsUserGroups/details-disabled', controller: 'formsUsergroupEdit'},
            {route: 'forms-usergroups/:id/edit', template: 'formsUserGroups/usergroup-add', controller: 'formsUsergroupEdit'},
            {route: 'forms-users', template: 'formsUsers/template', controller: 'formsUsers'},
            {route: 'forms-users/add', template: 'formsUsers/details', controller: 'formsUsersAdd'},
            {route: 'forms-users/:id', template: 'formsUsers/details-disabled', controller: 'formsUsersDetails'},
            {route: 'forms-users/:id/edit', template: 'formsUsers/details', controller: 'formsUsersEdit'},
            {route: 'forms', template: 'forms/template', controller: 'forms'},
            {route: 'forms/add', template: 'forms/forms-add', controller: 'formsAdd'},
            {route: 'forms/:id', template: 'forms/form', controller: 'form'},
            {route: 'forms/:id/records', template: 'forms/forms-records', controller: 'formsRecords'},
            {route: 'forms-procedures/:id/records', template: 'formsProcedures/procedures-records', controller: 'proceduresRecords'},
            {route: 'forms/:id/records/edit', template: 'forms/form', controller: 'formsRecordsEdit'},
            {route: 'forms-procedures/:id/records/edit', template: 'formsProcedures/procedure', controller: 'proceduresRecordsEdit'},
            {route: 'forms/:id/edit', template: 'forms/forms-add', controller: 'formsEdit'},
            {route: 'reporthome', template: 'reporthome/template', controller: 'reporthome'},
            {route: 'report_data', template: 'report_data/template', controller: 'report_data'},
            {route: 'report_show/:id', template: 'report_show/template', controller: 'report_show'},
            {route: 'report_edit/:id', template: 'report_edit/template', controller: 'report_edit'}
            
        ],
        easyRoutes: ['organizations', 'users']
    };
}